((twod, k) => { if(window[k]) return; window[k] = true;(()=>{"use strict";function e(e,t,n,o,s,r,i){try{var c=r(e,i),a=kt(c,"value")}catch(e){return void n(e)}kt(c,"done")?t(a):an(new dn((e=>e(a))),o,s)}function t(t){const n=function(){var n=this,o=arguments;return new dn((function(s,r){function i(t){e(a,s,r,i,c,ln,t)}function c(t){e(a,s,r,i,c,un,t)}var a=$t(t,n,o);i(void 0)}))};return Tt(n,"apply",(function(e,t){return $t(n,e,t)})),n}function n(e,t){let n,o=!0;return"boolean"==typeof e?(o=e,n=t):n=e,Xn((e=>{const t=bn(bt.document)
;"interactive"==t||"complete"==t?(n&&n(),e()):Fn.addEventListener("DOMContentLoaded",(()=>{n&&n(),e()}),At({capture:o,once:!0}))}))}const o=["chrome"],s=e=>{const t=Object.call,n=t.bind(t),o=Object.assign,s=Object.getOwnPropertyDescriptor,r=Object.getPrototypeOf,i=e=>o({__proto__:null},e),c=r(function*(){}()),a=r(Uint8Array.prototype);return i({sourceWindow:e,cSO:i,F_c:n,F_a:Object.apply,F_b:Object.bind,F_tS:Function.toString,A_fE:[].forEach,A_so:[].some,A_sh:[].shift,A_j:[].join,
A_iO:[].indexOf,A_iA:Array.isArray,O_a:o,O_k:Object.keys,O_v:Object.values,O_dP:Object.defineProperties,O_dPy:Object.defineProperty,O_hOP:Object.hasOwnProperty,O_gOPN:Object.getOwnPropertyNames,O_gOPD:s,O_gOPDs:Object.getOwnPropertyDescriptors,O_gPO:r,O_tS:{}.toString,J_p:JSON.parse,J_s:JSON.stringify,M_f:Math.floor,M_r:Math.random,M_m:Math.max,M_mi:Math.min,N_tS:(0).toString,N_MSI:Number.MAX_SAFE_INTEGER,P_t:Promise.prototype.then,P_c:Promise.prototype.catch,P_co:Promise.prototype.constructor,
G_n:c.next,G_t:c.throw,R_rABS:FileReader.prototype.readAsBinaryString,R_rAT:FileReader.prototype.readAsText,R_r:s(FileReader.prototype,"result").get,R_enq:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.enqueue:null,R_cl:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.close:null,S_fCC:String.fromCharCode,S_sl:"".slice,S_su:"".substr,S_sp_nr:"".split,S_iO:"".indexOf,S_tr:"".trim,S_r_nr:"".replace,S_rA_nr:"".replaceAll,
S_cCA:"".charCodeAt,S_tLC:"".toLowerCase,S_tUC:"".toUpperCase,Y_tST:Symbol.toStringTag,Y_unsc:Symbol.unscopables,USP_tS:URLSearchParams.prototype.toString,D_pFS:DOMParser.prototype.parseFromString,U_cOU:URL.createObjectURL,U_rOU:URL.revokeObjectURL,X_o:XMLHttpRequest.prototype.open,X_pSD:XMLHttpRequest.prototype.DONE,X_pSH:XMLHttpRequest.prototype.HEADERS_RECEIVED,X_pSL:XMLHttpRequest.prototype.LOADING,X_pSO:XMLHttpRequest.prototype.OPENED,X_pSU:XMLHttpRequest.prototype.UNSENT,
X_s:XMLHttpRequest.prototype.send,D_n:Date.now,I_tS:e=>""+e,E_r:Element.prototype.remove,E_s:Element.prototype.setAttribute,E_rA:Element.prototype.removeAttribute,D_cS:s(Document.prototype,"currentScript").get,D_gRS:s(Document.prototype,"readyState").get,D_cE:Document.prototype.createElementNS,D_gEBT:Document.prototype.getElementsByTagName,M_rT:s(MouseEvent.prototype,"relatedTarget").get,C_d:s(CustomEvent.prototype,"detail").get,P_p:s(PageTransitionEvent.prototype,"persisted").get,
C_pA:CustomEvent.prototype.AT_TARGET,M_d:MutationObserver.prototype.disconnect,W_aEL:addEventListener,W_rEL:removeEventListener,FD_e:FormData.prototype.entries,TA_b:s(a,"buffer").get,TA_sa:Uint8Array.prototype.subarray,parseInt,parseFloat,CustomEvent,CompositionEvent,KeyboardEvent,MouseEvent,MutationObserver,console:Object.assign({},console),Error,Uint8Array,Blob,ReadableStream,Number,String,Proxy,Window,FileReader,DOMParser,XMLHttpRequest,Function,RegExp,Promise,encodeURIComponent,
decodeURIComponent,encodeURI,decodeURI,escape,unescape,atob,btoa,setTimeout,clearTimeout,setInterval,clearInterval,postMessage,dispatchEvent,alert,prompt,confirm,close,getElementById:e.Document.prototype.getElementById,createEvent:e.Document.prototype.createEvent,createElement:e.Document.prototype.createElement})},r="vault"in twod;if(r&&void 0===twod.vault)throw"Invalid vault"
;const i=twod.vault=twod.vault||s(twod.unsafeWindow),{cSO:c,F_c:a,F_a:d,F_b:l,F_tS:u,A_fE:p,A_so:g,A_sh:m,A_j:f,A_iO:h,A_iA:v,O_a:_,O_k:b,O_v:w,O_dP:y,O_dPy:M,O_hOP:L,O_gOPN:E,O_gOPD:I,O_gOPDs:S,O_gPO:O,O_tS:x,J_p:D,J_s:R,M_f:j,M_r:P,M_m:C,M_mi:$,N_tS:A,N_MSI:T,P_t:U,P_c:k,P_co:B,G_n:F,G_t:X,R_rABS:N,R_rAT:q,R_r:W,R_enq:H,R_cl:G,S_fCC:J,S_sl:K,S_su:z,S_iO:Y,S_sp_nr:V,S_tr:Z,S_rA_nr:Q,S_cCA:ee,S_tLC:te,S_tUC:ne,Y_tST:oe,Y_unsc:se,D_pFS:re,D_cS:ie,D_gRS:ce,D_cE:ae,D_gEBT:de,E_r:le,E_s:ue,E_rA:pe,C_pA:ge,M_d:me,C_d:fe,P_p:he,M_rT:ve,U_cOU:_e,U_rOU:be,USP_tS:we,X_o:ye,X_s:Me,X_pSD:Le,X_pSH:Ee,X_pSL:Ie,X_pSO:Se,X_pSU:Oe,D_n:xe,I_tS:De,W_aEL:Re,W_rEL:je,FD_e:Pe,TA_b:Ce,TA_sa:$e,parseInt:Ae,parseFloat:Te,console:Ue,encodeURIComponent:ke,decodeURIComponent:Be,encodeURI:Fe,decodeURI:Xe,escape:Ne,unescape:qe,atob:We,btoa:He,postMessage:Ge,dispatchEvent:Je,alert:Ke,prompt:ze,confirm:Ye,close:Ve,getElementById:Ze,createEvent:Qe,createElement:et,CustomEvent:tt,CompositionEvent:nt,KeyboardEvent:ot,MouseEvent:st,MutationObserver:rt,Uint8Array:it,FileReader:ct,DOMParser:at,XMLHttpRequest:dt,Function:lt,RegExp:ut,Blob:pt,ReadableStream:gt,Number:mt,String:ft,Proxy:ht,Window:vt}=i,_t=twod,{unsafeWindow:bt,unsafeThis:wt}=_t,yt=a,Mt=d,Lt=b,Et=w,It=_,St=M,Ot=E,xt=I,Dt=O,Rt=v,jt=P,Pt=C,Ct=$,$t=(e,t,n)=>yt(Mt,e,t,n),At=c,Tt=(e,t,n)=>(St(e,t,At({
value:n,configurable:!0,enumerable:!0,writable:!0})),e),Ut=(e,t)=>Zt(e,t)?e[t]:void 0,kt=(e,t)=>{const n=xt(e,t);return n?At(n).value:void 0},Bt=(e,t)=>{const n=(e,t,o)=>{const s=xt(e,t),r=s?At(s):void 0;let i;return r?r.enumerable?r.value:void 0:--o>=0&&(i=Dt(e))?n(i,t,o):void 0};return n(e,t,5)},Ft=e=>{const t=(t,...n)=>$t(e,t,n);return Tt(t,"wrappedJSObject",e),t},Xt=()=>e=>Ft(e),Nt=Ft(l),qt=D,Wt=Xt()(g),Ht=Xt()(m),Gt=(e,t)=>{const n=[];return Vt(e,(e=>{t(e)&&zt(n,e)})),n},Jt=(e,t,n)=>{
const o=e.length;let s=t||0;if(s>=o)return[];s<0&&(s=Pt(0,o+s));let r=void 0===n?o:n;r<0&&(r=Pt(0,o+r)),r>o&&(r=o);const i=At({});for(let t=s;t<r;t++)i[t]=kt(e,t);return Et(i)},Kt=Xt()(f),zt=(e,t)=>{let n=e.length||0;return Tt(e,n,t),n++,e.length=n},Yt=Xt()(h),Vt=Xt()(p),Zt=Xt()(L),Qt=Xt()(V),en=Xt()(K),tn=Ft(x),nn=Dt({}),on=e=>{const t=At(e),n=Ot(t);for(let e=0;e<n.length;e++){const o=n[e],s=t[o];null!==s&&"object"==typeof s&&Dt(s)===nn&&(t[o]=on(s))}return t},sn=e=>{const t=Qt(tn(e)," ")
;return en(Kt(Jt(t,1)," "),0,-1)},rn=Xt()(u),cn=Xt()(A),an=Xt()(U),dn=(Xt()(k),Nt(B,Dt((async()=>{})()))),ln=Xt()(F),un=Xt()(X),pn=Xt()(N),gn=(Xt()(q),Xt()(W)),mn=(H&&Xt()(H),G&&Xt()(G),J),fn=Xt()(z),hn=Xt()(Y),vn=(Xt()(Z),Xt()(Q||function(e,t){return Kt(Qt(this,e),t)}),Xt()(ee)),_n=Xt()(te),bn=(Xt()(ne),Ft(re),Ft(ie),Ft(ce)),wn=Ft(ae),yn=Ft(de),Mn=(Ft(le),Ft(ue),Ft(pe),Ft(ve)),Ln=Ft(fe),En=Ft(he),In=me?Xt()(me):me,Sn=_e,On=be,xn=(Ft(we),Ft(Pe),Ft(Ce)),Dn=(Xt()($e),Xt()(ye),Xt()(Me),
xe),Rn=tt,jn=st,Pn=it,Cn=rt,$n=pt,An=ut,Tn=function(e,t){return kt(e,t)},Un=At({addEventListener:!1,Array:!0,Blob:!0,close:!1,CustomEvent:!0,Date:!0,DOMParser:!0,Error:!0,Event:!0,FileReader:!0,KeyboardEvent:!0,location:!0,Math:!0,MouseEvent:!0,Number:!0,Object:!0,ReadableStream:!0,removeEventListener:!1,Uint8Array:!0,XMLHttpRequest:!0}),kn=((()=>{const e=At({getElementById:Ze,createEvent:Qe,createElement:et,dispatchEvent:Je,addEventListener,removeEventListener}),t=At({});Vt(Lt(e),(n=>{try{
const o=e[n];t[n]=function(...e){return $t(o,bt.document,e)}}catch(e){t[n]=((e,t)=>{if(Bn.error(`Tampermonkey sandbox preparation ${t?"("+t+") ":""}failed. This usually is caused by a third-party extension.`,e),t)return()=>{}})(e,`document.${n}`)}}))})(),At({top:!0,location:!0}));twod.bridges=twod.bridges||At({});const Bn=twod.console=twod.console||At({}),Fn=At({addEventListener:Nt(Re,bt),removeEventListener:Nt(je,bt)});Vt(Lt(kn),(async e=>{if(!Fn[e])try{const t=bt[e];if(null==t)return;Fn[e]=t
}catch(e){}})),Vt(Lt(Un),(async e=>{if(!Fn[e])try{let t=kt(bt,e);if(void 0===t&&(wt===bt||void 0===(t=kt(wt,e))))return;const n=Un[e];Fn[e]=!1===n&&"function"==typeof t?Nt(t,wt):t}catch(e){}}));const Xn=e=>{let t,n=[],o=!1;e((e=>{if(!o){if(n.length){const t=n;n=[],Vt(t,(t=>t(e)))}else t=e;o=!0}}));const s=At({then:e=>(o?e(t):zt(n,e),s)});return s},Nn=()=>cn(Dn()+19831206*jt()+1,36),qn=function(){var e=t((function*(e){yield null,e()}));return function(t){return e.apply(this,arguments)}
}(),Wn=(()=>{const{console:e,bridges:t}=twod,n=At({});let o;const s=(t,o,s,i)=>{let c,a=[],d=[],l=[],u=[];const p=()=>{d=[],l=[],u=[],h(),y=null,delete n[o]},g=e=>{t.send("port.message",At({response_id:o,value:e}))},m=e=>{i&&"messageId"in e&&zt(a,e),g(e)},f=(e,t=!0)=>{c=e,t&&g(e)},h=()=>{c=void 0},v=At({addListener:e=>{zt(d,e)}}),_=At({addListener:e=>{zt(l,e)}}),b=At({addListener:e=>{zt(u,e)}}),w=()=>{p(),t.send("port.message",At({response_id:o,disconnect:!0}))};let y=At(s?{postMessage:m,
connectMessage:f,stopReconnecting:h,onMessage:v,onDisconnect:_,onReconnect:b,disconnect:w}:{postMessage:m,onMessage:v,onDisconnect:_,disconnect:w});return n[o]=At({message:t=>{if(i&&(e=>"ack"in e)(t)){const{messageId:n}=t;(t=>{if(!t)return void e.warn("PortMessaging: no message id in ack message");if(c&&c.messageId===t)return;let n=-1;Wt(a,((e,o)=>e.messageId===t&&(n=o,!0))),-1!==n?(Vt(Jt(a,0,n),(t=>e.warn(`PortMessaging: message ${t.messageId} was not ack'ed!`,t))),
a=Jt(a,n+1)):e.warn(`PortMessaging: no one is waiting for ${t}`)})(n)}d&&Vt(d,(e=>e(t)))},disconnect:()=>{if(c&&s)return r(s,o),f(c),i&&Vt(a,(e=>g(e))),void(u.length&&Vt(u,(e=>e())));l.length&&Vt(l,(e=>e())),p()}}),y},r=(e,n)=>{t.first.send("port.message",At({response_id:n,connect:!0,destination:e}))};return At({message:(t,r)=>{let i;if(t.connect){if(!t.destination||!t.response_id)throw"invalid message";o&&o(t.destination,s(r,t.response_id))}else{if(!t.response_id)throw"invalid message"
;if(!(i=n[t.response_id]))return void e.warn("ports: unknown id",t.response_id,t);t.disconnect?i.disconnect():i.message(t.value)}},connect:function(e,n,o){const i=Nn();return r(e,i),s(t.first,i,n?e:void 0,o)},onConnect:At({addListener:e=>{o=e}})})})(),{setInterval:Hn,setTimeout:Gn,clearInterval:Jn,clearTimeout:Kn,console:zn,cloneInto:Yn,exportFunction:Vn,createObjectIn:Zn,btoa:Qn}=bt,eo=Object.assign({},zn),to=Hn.bind(bt),no=Gn.bind(bt),oo=Jn.bind(bt),so=(Kn.bind(bt),
wt==bt.top),{arrayBuffer:ro,blob:io}=bt.Response.prototype,{arrayBuffer:co}=bt.Blob.prototype,{then:ao}=bt.Promise.prototype,{fetch:lo,location:uo,document:po,Response:go}=bt,mo=Ft(ro),fo=Ft(io),ho=Ft(co),vo=Yn,_o=(At({encode:e=>qe(ke(e)),decode:e=>Be(Ne(e))}),At({encode:e=>{let t="";for(let n=0;n<e.length;n++)t+=mn(255&vn(e,n));return He(t)},decode:e=>We(e)})),bo=e=>{const t=new Pn(e.length);for(let n=0;n<e.length;n++)t[n]=vn(e,n);return xn(t)},wo=e=>{let t;const n=Qt(e,","),o=Tn(n,0),s=Tn(n,1)
;t=-1!=hn(o,"base64")?We(s):qe(s);const r=Tn(Qt(o,":"),1),i=Tn(Qt(r,";"),0);return new $n([bo(t)],At({type:i}))},yo=(e,t)=>{const n=wn(bt.document,"http://www.w3.org/1999/xhtml",e);return"string"==typeof t?n.append(t):t&&Vt(Lt(t),(e=>{"textContent"==e?n.textContent=t[e]:n.setAttribute(e,t[e])})),n},Mo=e=>{const t=bt.document;if(t.body||"text/xml"==t.contentType)e();else{let t=!1;const o=new Cn((()=>{t=!0,Mo(e),(In||(e=>e.disconnect()))(o)}));o.observe(bt.document,At({childList:!0})),n((()=>{
t||((In||(e=>e.disconnect()))(o),e())}))}},Lo=e=>{n((()=>{no((()=>e()),1)}))};let Eo,Io;const So=uo.host,Oo=e=>{"n:"==fn(e,0,2)?Eo=fn(e,2):e&&(Io=fn(e,2))},xo=()=>Eo||(Io?(Eo=(e=>{const t=(e,t)=>e<<t|e>>>32-t,n=(e,t)=>{const n=2147483648&e,o=2147483648&t,s=1073741824&e,r=1073741824&t,i=(1073741823&e)+(1073741823&t);return s&r?2147483648^i^n^o:s|r?1073741824&i?3221225472^i^n^o:1073741824^i^n^o:i^n^o},o=(e,o,s,r,i,c,a)=>(e=n(e,n(n(((e,t,n)=>e&t|~e&n)(o,s,r),i),a)),
n(t(e,c),o)),s=(e,o,s,r,i,c,a)=>(e=n(e,n(n(((e,t,n)=>e&n|t&~n)(o,s,r),i),a)),n(t(e,c),o)),r=(e,o,s,r,i,c,a)=>(e=n(e,n(n(((e,t,n)=>e^t^n)(o,s,r),i),a)),n(t(e,c),o)),i=(e,o,s,r,i,c,a)=>(e=n(e,n(n(((e,t,n)=>t^(e|~n))(o,s,r),i),a)),n(t(e,c),o)),c=e=>{let t,n,o="",s="";for(n=0;n<=3;n++)t=e>>>8*n&255,s="0"+cn(t,16),o+=fn(s,s.length-2,2);return o};let a,d,l,u,p,g,m,f;const h=(e=>{let t;const n=e.length,o=n+8,s=16*((o-o%64)/64+1),r=[];for(let e=0;e<=s-1;e++)zt(r,0);let i=0,c=0;for(;c<n;)t=(c-c%4)/4,
i=c%4*8,r[t]=r[t]|vn(e,c)<<i,c++;return t=(c-c%4)/4,i=c%4*8,r[t]=r[t]|128<<i,r[s-2]=n<<3,r[s-1]=n>>>29,r})(e);p=1732584193,g=4023233417,m=2562383102,f=271733878;for(let e=0;e<h.length;e+=16)a=p,d=g,l=m,u=f,p=o(p,g,m,f,h[e+0],7,3614090360),f=o(f,p,g,m,h[e+1],12,3905402710),m=o(m,f,p,g,h[e+2],17,606105819),g=o(g,m,f,p,h[e+3],22,3250441966),p=o(p,g,m,f,h[e+4],7,4118548399),f=o(f,p,g,m,h[e+5],12,1200080426),m=o(m,f,p,g,h[e+6],17,2821735955),g=o(g,m,f,p,h[e+7],22,4249261313),
p=o(p,g,m,f,h[e+8],7,1770035416),f=o(f,p,g,m,h[e+9],12,2336552879),m=o(m,f,p,g,h[e+10],17,4294925233),g=o(g,m,f,p,h[e+11],22,2304563134),p=o(p,g,m,f,h[e+12],7,1804603682),f=o(f,p,g,m,h[e+13],12,4254626195),m=o(m,f,p,g,h[e+14],17,2792965006),g=o(g,m,f,p,h[e+15],22,1236535329),p=s(p,g,m,f,h[e+1],5,4129170786),f=s(f,p,g,m,h[e+6],9,3225465664),m=s(m,f,p,g,h[e+11],14,643717713),g=s(g,m,f,p,h[e+0],20,3921069994),p=s(p,g,m,f,h[e+5],5,3593408605),f=s(f,p,g,m,h[e+10],9,38016083),
m=s(m,f,p,g,h[e+15],14,3634488961),g=s(g,m,f,p,h[e+4],20,3889429448),p=s(p,g,m,f,h[e+9],5,568446438),f=s(f,p,g,m,h[e+14],9,3275163606),m=s(m,f,p,g,h[e+3],14,4107603335),g=s(g,m,f,p,h[e+8],20,1163531501),p=s(p,g,m,f,h[e+13],5,2850285829),f=s(f,p,g,m,h[e+2],9,4243563512),m=s(m,f,p,g,h[e+7],14,1735328473),g=s(g,m,f,p,h[e+12],20,2368359562),p=r(p,g,m,f,h[e+5],4,4294588738),f=r(f,p,g,m,h[e+8],11,2272392833),m=r(m,f,p,g,h[e+11],16,1839030562),g=r(g,m,f,p,h[e+14],23,4259657740),
p=r(p,g,m,f,h[e+1],4,2763975236),f=r(f,p,g,m,h[e+4],11,1272893353),m=r(m,f,p,g,h[e+7],16,4139469664),g=r(g,m,f,p,h[e+10],23,3200236656),p=r(p,g,m,f,h[e+13],4,681279174),f=r(f,p,g,m,h[e+0],11,3936430074),m=r(m,f,p,g,h[e+3],16,3572445317),g=r(g,m,f,p,h[e+6],23,76029189),p=r(p,g,m,f,h[e+9],4,3654602809),f=r(f,p,g,m,h[e+12],11,3873151461),m=r(m,f,p,g,h[e+15],16,530742520),g=r(g,m,f,p,h[e+2],23,3299628645),p=i(p,g,m,f,h[e+0],6,4096336452),f=i(f,p,g,m,h[e+7],10,1126891415),
m=i(m,f,p,g,h[e+14],15,2878612391),g=i(g,m,f,p,h[e+5],21,4237533241),p=i(p,g,m,f,h[e+12],6,1700485571),f=i(f,p,g,m,h[e+3],10,2399980690),m=i(m,f,p,g,h[e+10],15,4293915773),g=i(g,m,f,p,h[e+1],21,2240044497),p=i(p,g,m,f,h[e+8],6,1873313359),f=i(f,p,g,m,h[e+15],10,4264355552),m=i(m,f,p,g,h[e+6],15,2734768916),g=i(g,m,f,p,h[e+13],21,1309151649),p=i(p,g,m,f,h[e+4],6,4149444226),f=i(f,p,g,m,h[e+11],10,3174756917),m=i(m,f,p,g,h[e+2],15,718787259),g=i(g,m,f,p,h[e+9],21,3951481745),p=n(p,a),g=n(g,d),
m=n(m,l),f=n(f,u);const v=c(p)+c(g)+c(m)+c(f);return _n(v)})(`${So}#${Io}`),Eo):void 0),Do=e=>void 0!==kt(e,"objUrl"),Ro=e=>void 0!==kt(e,"blob"),jo=e=>void 0!==kt(e,"dataUri"),Po=e=>void 0!==e.binary,Co=globalThis;let $o,Ao,To,Uo,{chrome:ko,browser:Bo}=Co;To=()=>{if(void 0!==$o)return $o;try{const e=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);e&&($o=parseInt(e[2]))}catch(e){}return $o},Uo=()=>{if(void 0!==Ao)return Ao;try{Ao=-1!=navigator.userAgent.search(/Android|Mobile/)}catch(e){}
return Ao},To();const Fo=["chrome-extension:"];[].concat(["chrome"]);const Xo=(()=>{const e={getInternalPathRegexp:function(e,t){const n=new RegExp("(\\"+["/",".","+","?","|","(",")","[","]","{","}","\\"].join("|\\")+")","g"),o=Fo[0]+"//"+Xo.id+"/";return new RegExp(o.replace(n,"\\$1")+"([a-zA-Z"+(e?"\\/":"")+"]*)"+(t||"").replace(n,"\\$1"))},getInternalPageRegexp:function(){return Xo.getInternalPathRegexp(!1,".html")},getPlatformInfo:e=>ko.runtime.getPlatformInfo(e),getBrowserInfo:e=>{e({
name:"Chrome",version:`${To()}`,vendor:"unknown"})}};return Object.defineProperty(e,"lastError",{get:()=>ko.runtime.lastError,enumerable:!0}),Object.defineProperty(e,"id",{get:()=>ko.runtime.id,enumerable:!0}),Object.defineProperty(e,"short_id",{get:()=>e.id.replace(/[^0-9a-zA-Z]/g,"").substr(0,4),enumerable:!0}),e})(),No=(()=>{let e;return Object.defineProperties({},{inIncognitoContext:{get:()=>(void 0===e&&(e=ko.extension.inIncognitoContext),e),set:t=>{e=t},enumerable:!0},
...Object.getOwnPropertyDescriptors({getURL:function(e){return ko.runtime.getURL(e)},sendMessage:(e,t)=>ko.runtime.sendMessage(e,t),onMessage:{addListener:e=>ko.runtime.onMessage.addListener(e)},connect:e=>ko.runtime.connect({name:e}),urls:{prepareForReport:function(e){return e}}})})})();t((function*(e,t){yield ko.offscreen.createDocument({url:"offscreen.html",...e}),t&&t()})),t((function*(e){yield ko.offscreen.closeDocument(),e&&e()}))
;const qo=ko&&ko.userScripts&&ko.userScripts.onBeforeScript?{supported:!0,onBeforeScript:{addListener:e=>ko.userScripts.onBeforeScript.addListener(e)}}:{supported:!1},Wo=({sendPrefix:e,listenPrefix:n,send:o,onMessage:s})=>{if(void 0===o||void 0===s)throw"invalid args";let r,i,c=1;const a=At({}),d=At({}),l=e=>{e&&(r=e)},u=e=>{const t=++c;return d[c]=e,t};s(((t,s)=>t==`${n}_${r}`?(t=>{const{m:n,r:s,a:c,n:l}=t;if(a[n]&&(Vt(a[n],(e=>e(c))),delete a[n]),"message.response"==n){
if(null==s)throw"Invalid Message";((e,t)=>{let n;e&&(n=d[e])&&(n(t),delete d[e])})(s,c)}else if(i){const t=s?t=>{o(`${e}_${r}`,At({m:"message.response",a:t,r:s}))}:()=>{};i(At({method:n,args:c,node:l}),t)}})(s):null));const p=At({init:(g=t((function*(e){r?l():l(e)})),function(e){return g.apply(this,arguments)}),refresh:()=>null,switchId:e=>{r&&p.cleanup(),l(e)},send:(t,n,s,i)=>Xn((c=>{let a,d;"function"!=typeof s&&null!==s?(a=s,d=i):d=s,o(`${e}_${r}`,At({m:t,a:n,r:d?u(d):null,n:a})),c()})),
sendToId:(t,n,s)=>{o(`${e}_${t}`,At({m:n,a:s,r:null}))},once:(e,t)=>{a[e]||(a[e]=[]),zt(a[e],t)},setMessageListener:e=>{i=e},cleanup:()=>null});var g;return p},Ho=qo,Go=qo.supported&&!bt.pagejs;let Jo;const Ko=(e,t)=>{try{Jo(e),t&&t()}catch(e){t&&t(e.message||e)}},zo="u"+Nn(),{bridges:Yo}=twod;let Vo=[];const Zo=e=>{Ho.onBeforeScript.addListener((o=>{const s=(e,n)=>{Vt(t,(t=>t(e,n)))},r=e=>zt(n,At({listener:e,clone:o.export}));St(o.global,"pagejs",At({set:o.export((t=>{delete o.global.pagejs
;const n=o.metadata,{modes:i,nonce:c}=n;if(c&&Oo(c),Vt(Vo,(e=>e(t,n))),Vo=[],i.js){const n=At({unsafeWindow:o.global,unsafeThis:o.global.window,pageWindow:void 0,contextId:zo,fSend:s,fOnMessage:r,cloneInto:void 0,exportFunction:void 0});t(o.export(n)),Yo.js.sendToId(zo,"commid",At({id:e}))}})),configurable:!0})),Jo=o.global.eval}));const t=[],n=[],o=(e,t)=>{Vt(n,(({listener:n,clone:o})=>n(e,o(t))))},s=e=>zt(t,e);return At({createBridge:()=>{const t=Wo(At({sendPrefix:"2S",listenPrefix:"2U",
cloneInto:vo,send:o,onMessage:s}));return t.init(e),t}})};let Qo=[],es=[];const ts=e=>{const t=No.connect(e);if(Xo.lastError)return;let n=[];const o=At({postMessage:e=>t.postMessage(e),onMessage:At({addListener:e=>t.onMessage.addListener(e)}),onDisconnect:At({addListener:e=>{zt(n,e)}}),disconnect:()=>(s(!1),t.disconnect())}),s=e=>{e&&Vt(n,(e=>e())),n=[],Qo=Gt(Qo,(e=>e!==r)),es=Gt(es,(e=>e!==i))};t.onDisconnect.addListener((()=>s(!0)));const r=()=>{t.disconnect(),Xo.lastError,s(!0)};zt(Qo,r)
;const i=()=>{t.disconnect(),Xo.lastError};return zt(es,i),o};let ns,os,ss;Fn.addEventListener("pagehide",(e=>{En(e)&&Vt(es,(e=>e()))})),Fn.addEventListener("pageshow",(e=>{En(e)&&Vt(Qo,(e=>e()))}));const{console:rs}=twod,is=e=>Xn(function(){var n=t((function*(t){const n=e.url;let o,s,r,i;if(!n)return t(At({t:e,c:o}));const c=sn(n);if("string"==typeof n){const e=fn(n,0,5);if("blob:"===e)if(ss)s=At({objUrl:At({url:n})});else{const e=yield lo(n);i=yield fo(e)}else(ss||os)&&"data:"===e?i=wo(n):r=n
}else"Blob"==c||"File"==c?i=n:"ArrayBuffer"==c&&(i=new $n([n]));if(i)if(os)s=At({blob:i});else if(ss){const e=Sn(i);o=()=>On(e),s=At({objUrl:At({url:e})})}else{const e=yield(a=i,Xn((e=>{const t=new Fn.FileReader;t.onload=()=>{e(gn(t))},t.onerror=t=>{Bn.warn(`unable to decode data ${t}`),e("")},pn(t,a)}))),t=i.type||"application/octet-stream";try{s=At({dataUri:`data:${t};base64,${_o.encode(e)}`})}catch(e){rs.warn(`content: failed to get blob data from ${n}`,e)}}var a;t(At({t:At({url:r,tfd:s}),c:o
}))}));return function(e){return n.apply(this,arguments)}}()),cs=At({setInterval:e=>{let t;e.onMessage.addListener((n=>{"setInterval"==n.method&&(t=to(e.postMessage,n.t))})),e.onDisconnect.addListener((()=>{t&&oo(t),t=null}))},registerMenuCommand:e=>{const t=ts("registerMenuCommand");t?(t.onMessage.addListener((t=>{if("ack"in t)e.postMessage(t);else{const{method:n,event:o}=t;e.postMessage(At({method:n,event:o}))}})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{
const{messageId:n,name:o,uuid:s,accessKey:r,autoClose:i,title:c,id:a}=e,d=Kt([a,ns,s],"#");t.postMessage(At({messageId:n,method:"registerMenuCommand",name:o,title:c,uuid:s,menuId:d,accessKey:r,autoClose:i}))})),e.onDisconnect.addListener((()=>{t.disconnect()}))):no((()=>e.disconnect()),1)},notification:e=>{const t=ts("notification");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),
e.onDisconnect.addListener((()=>{t.disconnect()}))):no((()=>e.disconnect()),1)},openInTab:e=>{const t=ts("openInTab");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{const{messageId:n}=e;if("method"in e){const{method:o}=e;if("openInTab"==o)if("url"in e){let o=e.url;const{active:s,loadInBackground:r,insert:i,incognito:c,setParent:a}="boolean"==typeof e.options||void 0===e.options?At({loadInBackground:e.options
}):e.options,d=void 0===s?void 0!==r&&!r:s,l=void 0===i||i;o&&"//"==fn(o,0,2)&&(o=uo.protocol+o),t.postMessage(At({messageId:n,method:"openInTab",details:At({url:o,options:At({active:!!d,insert:!!l,incognito:!!c,setParent:!c&&!!a})}),uuid:e.uuid}))}else t.postMessage(e);else rs.warn(`content: unknown method ${o}`)}else"name"in e?t.postMessage(At({messageId:n,name:e.name})):"focus"in e?t.postMessage(At({messageId:n,focus:!0})):"close"in e&&t.postMessage(At({messageId:n,close:!0}))})),
e.onDisconnect.addListener((()=>{t.disconnect()}))):no((()=>e.disconnect()),1)},download:e=>{let t;const n=ts("download");if(!n)return void no((()=>e.disconnect()),1);let o;n.onMessage.addListener((t=>{e.postMessage(t)})),n.onDisconnect.addListener((()=>{e.disconnect(),t=!0})),e.onMessage.addListener((e=>{if("cancel"in e)t=!0,n.postMessage(At({cancel:!0,id:ns,uuid:e.uuid}));else if("details"in e){const{details:s,messageId:r,uuid:i}=e;is(s).then((({t:e,c})=>{if(t)return void(c&&c());o=c
;const{url:a,...d}=s;n.postMessage(At({messageId:r,method:"download",details:At({...d,from:e}),id:ns,uuid:i,location:uo.href}))}))}else n.postMessage(At({messageId:e.messageId,method:"download",uuid:e.uuid,id:e.id}))})),e.onDisconnect.addListener((()=>{o&&o(),o=void 0,n.disconnect()}))},webRequest:e=>{const t=ts("webRequest");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{const{messageId:n,rules:o,uuid:s}=e
;t.postMessage(At({messageId:n,method:"webRequest",rules:o,uuid:s}))})),e.onDisconnect.addListener((()=>{t.disconnect()}))):no((()=>e.disconnect()),1)},xhr:e=>{let n,o;const s=[];let r;const i=function(){var e=t((function*(e){if(e&&zt(s,e),o)yield o,i();else{const e=Ht(s);e&&e()}}));return function(t){return e.apply(this,arguments)}}(),c=ts("xhr");c?(c.onMessage.addListener((n=>{"ack"in n?e.postMessage(n):i((()=>{const{onpartial:s,data:r,...i}=n;let c;if(s&&r){const{tfd:n}=r;if(n){
const r=(e=>e&&(Ro(e)||Do(e)||jo(e)||Po(e))?(e=>{let t,n,o,s,r;if(Do(e))t=e.objUrl.url;else if(Ro(e))n=e.blob;else if(jo(e))o=e.dataUri;else{if(!Po(e))throw"incompatible TransferableData";s=e.binary,r=e.type}return At({toBlob:()=>Xn((e=>{if(n)e(n);else if(t)try{an(lo(t),(t=>{an(fo(t),(t=>{e(t)}))}))}catch(t){e(void 0)}else if(o)e(wo(o));else{if(void 0===s)throw"incompatible Transferable";{const t=bo(s);e(new $n([t],r?At({type:r}):void 0))}}})),dispose:()=>{t&&On(t),t=n=o=s=void 0}})
})(e):void 0)(n);if(!r)return;return void(o=Xn(function(){var n=t((function*(t){const n=()=>{o=null,t(),r&&r.dispose()};try{const t=yield r.toBlob();if(!t)return void n();const o=t.type;let a;if(a="arrayBuffer"in t?yield ho(t):yield mo(new go(t)),!a)return void n();c=At({nada:At({buffer:a,type:o})}),e.postMessage(At({...i,onpartial:s,data:c})),n()}catch(e){rs.warn(e),n()}}));return function(e){return n.apply(this,arguments)}}()))}c=r}else c=r;e.postMessage(At({...i,onpartial:s,data:c}))}))})),
c.onDisconnect.addListener((()=>{i(function(){var o=t((function*(){e.disconnect(),n=!0}));return function(){return o.apply(this,arguments)}}())})),e.onMessage.addListener((e=>{Go&&(e=((e,t=[])=>{const n=(e,o)=>{if(null===e)return null;if("object"==typeof e){const s=sn(e);if(-1!=Yt(t,s))return e;if(o){if(-1!==Yt(o,e))throw"Converting circular structure to clone";Tt(o,o.length,e)}else o=[e];if(Rt(e)){const t=[];for(let s=0;s<e.length;s++){let r;r=Zt(e,s)?Ut(e,s):Bt(e,s);const i=n(r,o);zt(t,i)}
return o.length-=1,t}if("Object"===s){const t=At({});return Vt(Lt(e),(s=>{const r=n(e[s],o);void 0!==r&&(t[s]=r)})),o.length-=1,t}throw`Unsupported type in clone: ${s}`}return e};return n(e)})(e,["Blob","File","ArrayBuffer"]));const{details:t}=e;(t?is(t):Xn((e=>e()))).then((o=>{const{t:s,c:i}=o||At({});if(n)return void(i&&i());let a,d;r=i,s&&t?(a=At({...t,...s}),d=At({...e,details:a,location:uo.href})):d=e,c.postMessage(d)}))})),e.onDisconnect.addListener((()=>{r&&r(),r=void 0,c.disconnect()
}))):no((()=>e.disconnect()),1)},onurlchange:e=>{const t=ts("onurlchange");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):no((()=>e.disconnect()),1)},onaudiostatechange:e=>{const t=ts("onaudiostatechange");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{
t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):no((()=>e.disconnect()),1)},values:e=>{const t=ts("values");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):no((()=>e.disconnect()),1)},backgroundControl:e=>{const t=ts("backgroundControl");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),
t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):no((()=>e.disconnect()),1)},keepAlive:e=>{const t=ts("keepAlive");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e),Xo.lastError})),e.onDisconnect.addListener((()=>{t.disconnect()}))):no((()=>e.disconnect()),1)}}),as=At({
setTimeout:({args:e,cb:t})=>{no(t,e.t)},setClipboard:({args:e,cb:t})=>{const{content:n,info:o,uuid:s}=e;let r,i;"object"==typeof o?(o.type&&(r=o.type),o.mimetype&&(i=o.mimetype)):"string"==typeof o&&(r=o);const c=i||("html"==r?"text/html":"text/plain");bt.document.addEventListener("copy",(e=>{e.stopImmediatePropagation(),e.preventDefault(),e.clipboardData&&e.clipboardData.setData(c,n)}),At({capture:!0,once:!0})),bt.document.execCommand("copy"),t()},closeTab:({args:{uuid:e},cb:t})=>{
No.sendMessage(At({method:"closeTab",uuid:e,id:ns}),(e=>{e&&e.error&&rs.warn(e.error),t(e)}))},focusTab:({args:{uuid:e},cb:t})=>{No.sendMessage(At({method:"focusTab",uuid:e,id:ns}),(e=>{e&&e.error&&rs.warn(e.error),t(e)}))},navigateTab:({args:{uuid:e,url:t,location:n},cb:o})=>{No.sendMessage(At({method:"navigateTab",uuid:e,url:t,location:n,id:ns}),(e=>{e&&e.error&&rs.warn(e.error),o(e)}))},addElement:(ds=t((function*({args:e,node:t,cb:o}){try{const s=yo(e.tag,At({...e.properties||At({}),
...e.id?At({id:e.id}):At({})}));let r,i;if("script"===e.tag&&(r=xo())&&s.setAttribute("nonce",r),t)i=t;else{const e=bt.document;if(i=e.head||e.body||e.documentElement,!i){const e=bt.document;i=yield Xn((t=>n((()=>t(e.head||e.body)))))}}i.appendChild(s),r&&s.removeAttribute("nonce"),o()}catch(e){rs.warn("content: error adding script",e)}})),function(){return ds.apply(this,arguments)}),tabs:({args:e,cb:t})=>{e.method="tabs",No.sendMessage(e,(e=>e&&t(e.data)))},cookie:({args:e,cb:t})=>{
e.method="cookie",No.sendMessage(e,(e=>e&&t(e.data)))},audio:({args:e,cb:t})=>{e.method="audio",No.sendMessage(e,(e=>e&&t(e.data)))}});var ds;const ls=At({init:()=>{ns=twod.contextId},setup:(e,t)=>{os=e,ss=t},processMessage:({method:e,args:t,node:n},o)=>{let s;if(s=as[e])return s(At({args:t,node:n,cb:o}));rs.warn(`content: unknown method ${e}`),o()},processConnect:(e,t)=>{let n;if(n=cs[e])return n(t)}
}),us=["GM_info","GM.info"],ps=["unsafeWindow","navigate",...us],gs=e=>e.replace(new RegExp("[\"']","g"),"\\$1");let ms=!1;const fs=(e,n,o,s,r)=>{const{console:i}=twod;ms=ms||e.logLevel>=60;const{version:c,injectMode:a,inIncognitoContext:d,isFirstPartyIsolation:l,downloadMode:u,relaxedCsp:p,userAgent:g,container:m,logLevel:f}=e,h=At({version:c,injectMode:a,inIncognitoContext:d,isFirstPartyIsolation:l,downloadMode:u,relaxedCsp:p,container:m});Vt(n,function(){var n=t((function*(t){
const{script:n,storage:c}=t,{name:a,uuid:d,options:{run_at:l}}=n,{requires:u,...p}=n,m=u.length,v=!n.options.unwrap,_=At({...h,userAgent:g,logLevel:f,sandboxMode:r});let b,w;const y=((e,t)=>{const{measure_scripts:n,top_level_await:o,enforce_strict_mode:s}=e,{source_url:r,script:i,code:c}=t,{name:a,grant:d}=i,{requires:l}=i,u=!i.options.unwrap,p=l.map((e=>e.textContent||"")).join("\n");if(u){let e="";const t=["define","module","exports"],l=t.map((()=>"undefined")),u=-1!==i.grant.indexOf("none")
;let g;return g=u?us:d.concat(ps),g.forEach((e=>{const n=e.split(".")[0];"window"!==n&&-1===t.indexOf(n)&&(t.push(n),l.push(`p.${n}`))})),
[`with (${u?"this.s":"this"}) {`,"(async (u, { p, r, s }) => {","try {",n?`console.time("${e=`SCRIPT RUN TIME[${gs(a)}]`}");\n`:"","r(u, s, [",l.join(","),"]);",n?`console.timeEnd("${e}");\n`:"","} catch (e) {","if (e.message && e.stack) {","console.error(\"ERROR: Execution of script '",gs(a),"' failed! \" + e.message);","console.log(e.stack);","} else {","console.error(e);","}","}","})","(",(o?"async ":"")+"function(",t.join(","),") {",s?'"use strict";\n':"\n",p,c,"\n",`}, ${u?"this":"seed"})`,"}","\n",r?`//# sourceURL=${r}\n`:""].join("")
}return[p,c,"\n",r?`//# sourceURL=${r}\n`:""].join("")})(e,t);return v?(b=()=>{ms&&i.debug(`env: inject "${a}" now`);const e=`__f__${Nn()}`,t=At({storage:c,script:p}),n=`window["${e}"] = function(){${y}}`;let r=!0;s.once(`scriptack-${e}`,(()=>{ms&&!r&&i.log(`env: execution of "${a}" was delayed`),o(n,(e=>{e&&i.error(`Uncaught SyntaxError: ${e}`)}))})),s.send("script",At({id:e,unwrap:!1,bundle:t,flags:_})),r=!1},w="context-menu"==l||"document-start"==l?void 0:()=>{
ms&&i.debug(`env: run "${a}" now  (${m} requires)`),s.send("run",At({uuid:d}))}):w=()=>{ms&&i.debug(`env: inject @unwrap "${a}" now`),o(y,(e=>{e&&i.error(`Uncaught SyntaxError: ${e}`)}))},hs(a,l,b,w,ms)}));return function(e){return n.apply(this,arguments)}}())},hs=(e,t,o,s,r)=>{const{console:i}=twod;let c;"document-start"==t?(r&&i.debug(`env: run "${e}" ASAP -> document-start`),c=e=>e()):"document-body"==t?(r&&i.debug(`env: schedule "${e}" for document-body`),
c=Mo):"context-menu"==t?r&&i.debug(`env: run "${e}" ASAP -> context-menu`):"document-end"==t?(r&&i.debug(`env: schedule "${e}" for document-end`),c=e=>n(!1,e)):(r&&i.debug(`env: schedule "${e}" for document-idle`),c=Lo),o&&o(),s&&c&&c((()=>{s()}))},vs=(e,t)=>{let n,o;try{o=(0,eval)(e)}catch(e){n=e.message||e}return t&&t(n),o},_s=({sendPrefix:e,listenPrefix:n,cloneInto:o})=>{const s=e=>o?o(e,bt.document):e,i=At({});let c,a,d=1;const l=At({});let u=!1,p=[];const g=()=>{
b=bt.document.documentElement,u=!1;const e=p;p=[],Vt(e,(e=>{u||y()?zt(p,e):e()}))};let m;const f=e=>{const t=++d;return l[d]=e,t},h=(e,t)=>{const{m:n,a:o,r,n:i}=t,{m:c,c:a}=((e,t,n)=>{let o,r;return n?(r=new jn(e,At({relatedTarget:n})),o=new Rn(e,At({detail:s(t)}))):o=new Rn(e,At({detail:s(t)})),At({m:r,c:o})})(e,At({m:n,a:o,r}),i);c&&$t(Je,bt,[c]),$t(Je,bt,[a])},v=t=>{const n=(e=>{if("MouseEvent"===sn(e)){const t=Mn(e);if(!t)throw"Invalid MouseEvent";return void(m=t)}const t=on(Ln(e))
;return m&&(t.n=m,m=void 0),t})(t);if(!n)return;const{m:o,r:s,a:r,n:d}=n;if(i[o]&&(Vt(i[o],(e=>e(r))),delete i[o]),"unlock"==o)h(`${e}_${a}`,At({m:"unlocked",a:void 0,r:null})),g();else if("unlocked"==o)g();else if("message.response"==o){if(null==s)throw"Invalid Message";((e,t)=>{let n;e&&(n=l[e])&&(n(t),delete l[e])})(s,r)}else if(c){const t=s?t=>{h(`${e}_${a}`,At({m:"message.response",a:t,r:s}))}:()=>{};c(At({method:o,args:r,node:d}),t)}},_=e=>{e&&(a=e),a&&Fn.addEventListener(`${n}_${a}`,v,!0)
};let b,w;const y=()=>{if((()=>{const e=bt.document.documentElement;return b||(b=e),b!==e})()){if(w){const e=w;w=void 0,e(bt.document)}return!0}},M=e=>(b=bt.document.documentElement,Xn(function(){var n=t((function*(t){if(w=t,r&&!e&&(yield null,y()))return;const n=new Cn((()=>{y()&&n.disconnect()}));n.observe(bt.document,At({childList:!0}))}));return function(e){return n.apply(this,arguments)}}())),L=At({init:(E=t((function*(t,n){a?_():_(t),M(n).then((()=>{u=!0,L.refresh(),h(`${e}_${a}`,At({
m:"unlock",a:void 0,r:null}))}))})),function(e,t){return E.apply(this,arguments)}),refresh:()=>{const e=a;e&&(L.cleanup(),L.init(e,!0))},switchId:e=>{a&&L.cleanup(),_(e)},send:(t,n,o,s)=>Xn((r=>{let i,c;"function"!=typeof o&&null!==o?(i=o,c=s):c=o,y();const d=()=>{h(`${e}_${a}`,At({m:t,a:n,r:c?f(c):null,n:i})),r()};u?zt(p,d):d()})),sendToId:(t,n,o)=>{h(`${e}_${t}`,At({m:n,a:o,r:null}))},setMessageListener:e=>{c=e},once:(e,t)=>{i[e]||(i[e]=[]),zt(i[e],t)},cleanup:()=>{
a&&(Fn.removeEventListener(`${n}_${a}`,v,!0),a=void 0)}});var E;return L},bs=function(e,t,n,o,s){let r;const i=xo(),c=yo("script");i&&c.setAttribute("nonce",i);try{c.textContent=t,e.appendChild(c)}catch(e){r=e.message||e}if(i&&c.removeAttribute("nonce"),!s){const e=c.parentNode;e&&e.removeChild(c)}return o&&o(r),!r},ws=(e,t)=>{try{bs(po.head||po.body||po.documentElement||po,e,0,t)}catch(e){t&&t(e.message||e)}};let ys,Ms;const Ls=e=>{const t=ts("tabInfo");t?(t.onMessage.addListener((e=>{
if("ack"in e);else{const{info:t}=e;t?ys=on(t):eo.warn("tabInfo: unexpected message",e)}})),t.onDisconnect.addListener((()=>{Es()})),e(t)):no((()=>Ls(e)),100)},Es=()=>{Ls((e=>{ys=Ms||ys,Ms=void 0,e.postMessage(At({method:"tabInfo",messageId:Nn(),info:ys}))}))},Is=e=>{e=e||Fn.location.href;const t=ts("tabInfo");t?(t.onMessage.addListener((e=>{"ack"in e||eo.warn("tabInfo.frame: unexpected message",e)})),t.onDisconnect.addListener((()=>{Is(e)})),t.postMessage(At({method:"tabInfo",messageId:Nn(),
url:e}))):no((()=>Is(e)),100)};let Ss=!1;const Os=location.pathname+location.search;Xo.short_id,window.btoa(Os.length+Os).substr(0,255).replace(/[#=/]/g,"_");let xs=!1;const Ds=(e,t,o)=>{const{contextId:s,bridges:r,console:i}=twod;let c;Xn((n=>{const o=e=>{let t=1;const o=()=>{Ss&&i.log('content: send "prepare" message'),No.sendMessage({method:"prepare",id:s,topframe:so,url:window.location.href},(s=>{if(!xs){if(!s)return Ss&&i.log("content: _early_ execution, connection to bg failed -> retry!"),
window.setTimeout(o,t),void(t=Ct(2*t,3e3));xs=!0,s.nonce&&Oo(s.nonce),Lt(s.contexters).length||Lt(s.scripts).length||s.external_connect?(e&&e(s),n({info:s,type:"complete"==bn(bt.document)?"late":"normal"})):n({info:s})}}))};!function(e){const t=()=>"prerender"!==document.webkitVisibilityState,n=()=>{t()&&(document.removeEventListener("webkitvisibilitychange",n,!1),e())};t()?e():document.addEventListener("webkitvisibilitychange",n,!1)}(o)},r=()=>{let r
;if(Ss&&i.log("content: Started ("+s+", "+window.location.origin+window.location.pathname+")",wt.tm_info),r=wt.tm_info){delete wt.tm_info,r.nonce&&Oo(r.nonce);const{contexters:o,scripts:i}=r;if(Lt(o).length||Lt(i).length){if(r.contexters.raw||r.scripts.raw)if(e.raw)void 0===c&&(c=e.raw());else if(!t)throw"raw inject missing";n({info:r,type:"sync"})}else n({info:r});{let e;if("userscripts-dynamic"===r.contentMode){const t=e={};Vt(Lt(i),(e=>{const n=i[e]
;n&&Vt(n,(({script:{uuid:e,name:n}})=>t[e]=n))}))}No.sendMessage({method:"prepare",id:s,topframe:so,url:window.location.href,scripts:e,cleanup:!0},(()=>null))}}else t?o((({scripts:t,contexters:n})=>{e.raw&&void 0===c&&(t.raw||n.raw)&&(c=e.raw())})):(e.raw&&void 0===c&&(c=e.raw()),o())};t?window.setTimeout((()=>r()),1):r()})).then((({info:a,type:d})=>{const{external_connect:l}=a;if(!t&&(e=>{if(e){const t=location.href.split("#")[0];return e.some((({source:e,flags:n})=>{const o=new An(e,n)
;if(""===t.replace(o,""))return!0}))}return!1})(l)&&(void 0===c&&e.raw&&(c=e.raw()),c||i.warn("content: external connectability detected, but unable to initialize raw mode!"),qn((()=>r.first.send("external.connect")))),d){Ss=Ss||a.logLevel>=60;const{scripts:c,sharedBlobs:l,sharedObjectUrls:p}=a;if(ls.setup(l,p),c.raw){let n;t&&!e.raw&&(n=!0),n&&(e.js?(c.js=(c.js||[]).concat(c.raw||[]),delete c.raw):e.dom&&(c.dom=(c.dom||[]).concat(c.raw||[]),delete c.raw))}if(c.js){
if(!e.js)throw"js inject missing";e.js()}if(c.dom){if(!e.dom)throw"dom inject missing";e.dom()}n(!1,(()=>{Ss&&i.log("content: DOMContentLoaded"),Vt(Lt(r),(e=>r[e].send("DOMContentLoaded")))})),u=()=>{Ss&&i.log("content: load"),Vt(Lt(r),(e=>r[e].send("load")))},"complete"==bn(bt.document)?u():Fn.addEventListener("load",(()=>u()),At({capture:!0,once:!0}));const g=(c.dom||[]).length+(c.js||[]).length+(c.raw||[]).length
;Ss&&i.log("content: "+(d||"normal")+" start event processing for "+s+" ("+g+" to run)"),Rs(a,"sync"===d),!so&&g&&Is(location.href),o()}else o();var u}))},Rs=e=>{const{bridges:t}=twod,{scripts:n,...s}=e;n.js&&fs(s,n.js,Ko,t.js,"js"),n.dom&&(Vt(o,(e=>wt[e]=void 0)),fs(s,n.dom,vs,t.dom,"dom")),n.raw&&fs(s,n.raw,ws,t.raw,"raw")},js=function(){var e=t((function*(){const{contextId:e}=twod,{location:t,document:n}=bt;n.addEventListener("mouseenter",(()=>{try{No.sendMessage(At({method:"contextmenu",
url:t.href,id:e}),(()=>{}))}catch(e){}}),!1)}));return function(){return e.apply(this,arguments)}}();let Ps;t((function*(){const{unsafeWindow:e,bridges:t}=twod,{location:n,document:o}=e,r=o instanceof XMLDocument;if(!At({"http:":!0,"https:":!0,"file:":!0})[e.location.protocol])return;so&&(Es(),Fn.addEventListener("pagehide",(e=>{En(e)&&(Ms=ys)})));const i=twod.contextId?twod.contextId:twod.contextId=Nn();let c;const a=At({});It(twod.console,eo),Xn((n=>{if(Go){const{createBridge:e}=Zo(i)
;o=(o,s)=>{Ps=c=o;const{modes:i}=s;i.js&&(t.js=e(),a.js=()=>!1,r&&(i.raw=!1)),n(s)},zt(Vo,o)}else Xn((t=>{Ps=c=e.pagejs,delete e.pagejs,Ps?t():(()=>{let e=n=>{delete bt.pagejs,e=void 0,(e=>{if(!e)throw"Error: pagejs missing. Please see http://tmnk.net/faq#Q208 for more information.";Ps=c=e,t()})(n)};St(bt,"pagejs",At({set:e,configurable:!0})),no((()=>{e&&e()}),1)})()})).then((()=>{n(At({modes:At({js:!1,raw:!0,dom:!0})}))}));var o})).then((({modes:{dom:o,raw:d},answer:l})=>{var u
;if(l&&(u=l).scripts&&u.contexters&&(wt.tm_info=l),o){const e=Go?vs(`() => ${c};`)():c,{createBridge:n,inject:o}=((e,t)=>{const n=(e,t)=>{Vt(s,(n=>n(e,t)))},o=e=>zt(r,At({listener:e,clone:e=>e})),s=[],r=[],i=(e,t)=>{Vt(r,(({listener:n,clone:o})=>n(e,o(t))))},c=e=>zt(s,e),a="c"+Nn();let d;return At({createBridge:()=>(d=Wo(At({sendPrefix:"2S",listenPrefix:"2U",send:i,onMessage:c})),d.init(e),d),inject:()=>(t(At({unsafeWindow:bt,unsafeThis:wt,pageWindow:void 0,contextId:a,fSend:n,fOnMessage:o})),
d.sendToId(a,"commid",At({id:e})),!0)})})(i,e);a.dom=o,t.dom=n()}if(d){const{createBridge:e,inject:n}=((e,t)=>{let n;return At({createBridge:()=>(n=_s(At({sendPrefix:"2P",listenPrefix:"2C",cloneInto:vo})),n),inject:()=>{n.init(e);let o=!1;const r=Nn(),i="("+rn(((e,t)=>{const n=window,o=t(n),s=n.parent,{O_dPy:r,cSO:i}=o;r(s,e,i({value:o,enumerable:!1,writable:!1,configurable:!0}))}))+')("'+r+'", '+rn(s)+")";return n.once("ack",(()=>{o=!0})),(o=>{((e,t)=>{
const n=Tn(yn(bt.document,"*"),0)||bt.document,o=yo("div"),s=o.attachShadow(At({mode:"closed"}));s.appendChild(yo("style",":host { display: none }"));const r=yo("iframe",At({sandbox:"allow-scripts allow-same-origin",style:"display: none",src:"javascript:void 0"}));let i=()=>{if(null===i)return;i=null;let n=!1;try{const t=r.contentDocument,o=r.contentWindow;t&&o&&(n=bs(Tn(t.getElementsByTagName("*"),0),e))}catch(e){}t(o,n),r.remove(),o.remove()};r.addEventListener("load",i,At({once:!0,capture:!0
})),s.appendChild(r),n.appendChild(o),i&&i()})(o,((o,s)=>{bs(o,`((w, g) => {(${t})({ unsafeWindow: typeof g === "undefined" ? w : g, unsafeThis: w, vault: ${s?`w["${r}"]`:"null"}, contextId: "${r}", __proto__: null }); delete w["${r}"]; })(window, globalThis)\n`,0,(()=>{n.sendToId(r,"commid",At({id:e}))}),!0)}))})(i),o}})})(i,c);a.raw=n,t.raw=e()}const p=t.first=t.js||t.raw||t.dom;No.onMessage.addListener(((t,o,s)=>{
"executeScript"==t.method?(t.url&&0!==hn(n.href,t.url)||void 0!==t.topframe&&t.topframe!=so||Rs(t.info,!1),s(At({}))):so&&("loadUrl"==t.method?(e.location=t.url,s(At({}))):"reload"==t.method?(n.reload(),s(At({}))):"setForeignAttr"==t.method?(p.send(t.method,t),s(At({}))):eo.log("content: unknown method "+(e=>{const t=(e,n)=>{let o;if(null===e)o="null";else{const s=typeof e;if("object"===s){if(n){if(-1!=Yt(n,e))throw"Converting circular structure to JSON";Tt(n,n.length,e)}else n=[e];if(Rt(e)){
let s="";for(let o=0;o<e.length;o++){let r;r=Zt(e,o)?Ut(e,o):Bt(e,o);const i=t(r,n);s+=`${o?",":""}${void 0===i?"null":i}`}o=`[${s}]`}else{let s="";Vt(Lt(e),(o=>{const r=t(e[o],n);void 0!==r&&(s+=`${s?",":""}${R(o)}: ${r}`)})),o=`{${s}}`}n.length-=1}else{if("bigint"===s)throw"Do not know how to serialize a BigInt";o=R(e)}}return o};return t(e)})(t)))})),Wn.onConnect.addListener(((e,t)=>{ls.processConnect(e,t)})),ls.init(),Vt(Lt(t),(e=>{if("first"==e)return;const n=t[e]
;n.setMessageListener(((t,o)=>{const{method:s,args:r}=t;if("port.message"==s)Wn.message(r,n);else if("csp"==s){let t;t="raw"==e?ws:"dom"==e?vs:Ko,t(r.src,(e=>{e&&eo.error(`Uncaught Error: ${e}`)}))}else if("external.message"==s)No.sendMessage(At({method:"externalMessage",request:r}),(e=>{o(e)}));else if("console"==s){const e=r,t=Tn(e,0),n=Tn(e,1),o=eo[t]||eo.log;o&&$t(o,eo,((e,...t)=>{let n=e.length;const o=At(e);for(let e=0;e<t.length;e++){const s=t[e],r=Rt(s)?s:[s]
;for(let e=0;e<r.length;e++)o[n+e]=kt(r,e);n+=r.length}return Et(o)})(["injected:"],(e=>{const t=[];return Vt(e,(e=>{zt(t,(e=>"string"==typeof e?qt(e):e)(e))})),t})(n)))}else"commid"==s||(e=>"ack"==e.method||"injectableack"==e.method||0===hn(e.method,"scriptack-"))(t)||ls.processMessage(t,o)}))})),Ds(a,r,(()=>Ps=void 0)),js()}))}))()})();})({ __proto__: null, unsafeWindow: typeof globalThis === "undefined" ? window : globalThis, unsafeThis: window, }, "tm_nt7mbn")